# Generated by Django 3.0.2 on 2020-03-24 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("publishers", "0001_initial"),
        ("issues", "0002_fk_m2m"),
        ("story_arcs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyarc",
            name="first_issue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="first_appearance_story_arc",
                to="issues.Issue",
            ),
        ),
        migrations.AddField(
            model_name="storyarc",
            name="first_issue_name",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="storyarc",
            name="publisher",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_arcs",
                to="publishers.Publisher",
            ),
            preserve_default=False,
        ),
    ]
