# Generated by Django 3.0.4 on 2020-03-25 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("publishers", "0002_slug_overwrite_true"),
        ("story_arcs", "0002_fk_m2m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storyarc",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="story_arcs",
                to="publishers.Publisher",
            ),
        ),
    ]
