# Generated by Django 3.1.7 on 2021-03-11 11:30

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("story_arcs", "0004_storyarc_comicvine_last_match"),
    ]

    operations = [
        migrations.AlterField(
            model_name="storyarc",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from=["publisher__name", "name"]
            ),
        ),
    ]
