# Generated by Django 3.1.7 on 2021-03-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("story_arcs", "0006_auto_20210313_1737"),
    ]

    operations = [
        migrations.AddField(
            model_name="storyarc",
            name="first_issue_comicvine_id",
            field=models.IntegerField(null=True),
        ),
    ]
