# Generated by Django 3.0.4 on 2020-03-24 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("publishers", "0002_slug_overwrite_true"),
        ("teams", "0002_fk_m2m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="team",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teams",
                to="publishers.Publisher",
            ),
        ),
    ]
