version: '3'

volumes:
  local_postgres_data: {}
  local_postgres_data_backups: {}
  local_mongodb_data: { }
  local_mongodb_config: { }
  local_rabbitmq_data: { }
  gerapy_data: { }


services:
  django: &django
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: read_comics_local_django
    container_name: django
    depends_on:
      - postgres
      - redis
      - mailhog
      - celeryworker
      - rabbitmq
      - mongodb
    volumes:
      - .:/app:z
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.django_unsafe
      - ./.envs/.local/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: read_comics_production_postgres
    container_name: postgres
    volumes:
      - local_postgres_data:/var/lib/postgresql/data:Z
      - local_postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.local/.postgres
    ports:
      - "5432:5432"

  mongodb:
    image: mongo:8.0.4
    container_name: mongodb
    volumes:
      - ./compose/local/mongodb:/docker-entrypoint-initdb.d
      - local_mongodb_data:/data/db
      - local_mongodb_config:/data/configdb
      - ./compose/local/mongodb/secret.key:/data/db/secret.key
    env_file:
      - ./.envs/.local/.mongo
    ports:
      - "27017:27017"


  #  docs:
#    image: read_comics_local_docs
#    container_name: docs
#    build:
#      context: .
#      dockerfile: ./compose/local/docs/Dockerfile
#    env_file:
#      - ./.envs/.local/.django
#    volumes:
#      - ./docs:/docs:z
#      - ./config:/app/config:z
#      - ./read_comics:/app/read_comics:z
#    ports:
#      - "7001:7001"
#    command: /start-docs

  mailhog:
    image: mailhog/mailhog:v1.0.0
    container_name: mailhog
    ports:
      - "8025:8025"

  redis:
    image: redis:6
    container_name: redis

  rabbitmq:
    hostname: rabbitmq
    container_name: rabbitmq
    image: rabbitmq:4-management
    env_file:
      - ./.envs/.local/.rabbit_unsafe
    volumes:
      - local_rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672" # Management UI
      - "5672:5672"   # Default RabbitMQ Port

  celeryworker:
    <<: *django
    image: read_comics_local_celeryworker
    container_name: celeryworker
    depends_on:
      - rabbitmq
      - postgres
      - mailhog
    ports: []
    environment:
      QUEUES: read_comics_default,read_comics_spiders,read_comics_characters,read_comics_concepts,read_comics_issues,read_comics_locations,read_comics_objects,read_comics_people,read_comics_powers,read_comics_publishers,read_comics_story_arcs,read_comics_teams,read_comics_volumes
    command: /start-celeryworker

#  celerybeat:
#    <<: *django
#    image: read_comics_local_celerybeat
#    container_name: celerybeat
#    depends_on:
#      - redis
#      - postgres
#      - mailhog
#    ports: []
#    command: /start-celerybeat

  flower:
    <<: *django
    image: read_comics_local_flower
    container_name: flower
    ports:
      - "5555:5555"
    command: /start-flower
