version: '3'

volumes:
  production_traefik: {}

services:
  django: &django
    image: registry.digitalocean.com/read-comics/app:latest
    depends_on:
      - redis
    env_file:
      - .env
    command: /start

  traefik:
    image: registry.digitalocean.com/read-comics/traefik:latest
    depends_on:
      - django
    volumes:
      - production_traefik:/etc/traefik/acme:z
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:5555:5555"

  redis:
    image: redis:6
    container_name: redis

  celeryworker:
    <<: *django
    command: /start-celeryworker

  celerybeat:
    <<: *django
    command: /start-celerybeat

  flower:
    <<: *django
    command: /start-flower
