version: '3'

volumes:
#  production_postgres_data: {}
#  production_postgres_data_backups: {}
  production_traefik: {}

services:
  app:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: cr.yandex/crpkef6i6mmeq12lo3i7/app

  traefik:
    build:
      context: .
      dockerfile: ./compose/production/traefik/Dockerfile
    image: cr.yandex/crpkef6i6mmeq12lo3i7/traefik
