# Generated by Django 3.1.5 on 2021-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("publishers", "0002_slug_overwrite_true"),
    ]

    operations = [
        migrations.AddField(
            model_name="publisher",
            name="comicvine_last_match",
            field=models.DateTimeField(null=True),
        ),
    ]
