# Generated by Django 3.0.2 on 2020-03-22 17:39

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("publishers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Character",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comicvine_id", models.IntegerField(unique=True)),
                ("comicvine_url", models.URLField(max_length=1000)),
                ("comicvine_matched", models.BooleanField(default=False)),
                ("created_dt", models.DateTimeField(auto_now_add=True)),
                ("modified_dt", models.DateTimeField(auto_now_add=True)),
                ("name", models.TextField(null=True)),
                ("real_name", models.TextField(null=True)),
                ("aliases", models.TextField(null=True)),
                ("short_description", models.TextField(null=True)),
                ("html_description", models.TextField(null=True)),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(0, "Other"), (1, "Male"), (2, "Female")], null=True
                    ),
                ),
                ("birth", models.DateField(null=True)),
                ("origin", models.TextField(null=True)),
                ("thumb_url", models.URLField(max_length=1000, null=True)),
                ("image_url", models.URLField(max_length=1000, null=True)),
                ("first_issue_name", models.TextField(null=True)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from=["name"]
                    ),
                ),
                (
                    "character_enemies",
                    models.ManyToManyField(
                        related_name="_character_character_enemies_+",
                        to="characters.Character",
                    ),
                ),
                (
                    "character_friends",
                    models.ManyToManyField(
                        related_name="_character_character_friends_+",
                        to="characters.Character",
                    ),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="publishers.Publisher",
                    ),
                ),
            ],
            options={
                "ordering": ("name",),
            },
        ),
    ]
