# Generated by Django 3.0.2 on 2020-03-24 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0001_initial"),
        ("powers", "0001_initial"),
        ("publishers", "0001_initial"),
        ("issues", "0001_initial"),
        ("teams", "0001_initial"),
        ("characters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="creators",
            field=models.ManyToManyField(
                related_name="created_characters", to="people.Person"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="first_issue",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="first_appearance_characters",
                to="issues.Issue",
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="powers",
            field=models.ManyToManyField(related_name="characters", to="powers.Power"),
        ),
        migrations.AddField(
            model_name="character",
            name="team_enemies",
            field=models.ManyToManyField(
                related_name="character_enemies", to="teams.Team"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="team_friends",
            field=models.ManyToManyField(
                related_name="character_friends", to="teams.Team"
            ),
        ),
        migrations.AddField(
            model_name="character",
            name="teams",
            field=models.ManyToManyField(related_name="characters", to="teams.Team"),
        ),
        migrations.AlterField(
            model_name="character",
            name="publisher",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="characters",
                to="publishers.Publisher",
            ),
        ),
    ]
