# Generated by Django 3.1.7 on 2021-03-11 11:30

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("volumes", "0004_volume_comicvine_last_match"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="volume",
            options={"ordering": ("publisher__name", "name", "start_year")},
        ),
        migrations.AlterField(
            model_name="volume",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                populate_from=["publisher__name", "name", "start_year"],
            ),
        ),
    ]
