# Generated by Django 3.1.7 on 2021-03-15 10:29

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("volumes", "0007_auto_20210315_0750"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volume",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                overwrite=True,
                populate_from=["get_publisher_name", "name", "start_year"],
            ),
        ),
    ]
