# Generated by Django 3.1.7 on 2021-04-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("volumes", "0010_auto_20210329_2319"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="volume",
            options={"ordering": ("name", "start_year")},
        ),
    ]
