# Generated by Django 3.2.9 on 2021-12-12 00:27

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("volumes", "0012_alter_volume_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volume",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=1000,
                overwrite=True,
                populate_from=["get_publisher_name", "name", "start_year"],
                unique=True,
            ),
        ),
    ]
