# Generated by Django 3.2.9 on 2022-09-01 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("volumes", "0014_auto_20220121_1956"),
    ]

    operations = [
        migrations.AlterField(
            model_name="volume",
            name="last_issue_number",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
