# Generated by Django 3.2.9 on 2021-12-07 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missing_issues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="missingissue",
            name="volume_comicvine_id",
            field=models.IntegerField(),
        ),
    ]
