# Generated by Django 3.2.9 on 2021-12-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_issues', '0003_auto_20211207_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ignoredissue',
            name='volume_start_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ignoredvolume',
            name='start_year',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='missingissue',
            name='volume_start_year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
