# Generated by Django 3.2.9 on 2021-12-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_issues', '0004_auto_20211207_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ignoredissue',
            name='number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='missingissue',
            name='number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
