# Generated by Django 3.2.9 on 2021-12-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("missing_issues", "0008_missingissue_numerical_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="missingissue",
            name="skip",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="missingissue",
            name="skip_date",
            field=models.DateField(null=True),
        ),
    ]
