# Generated by Django 3.2.9 on 2021-12-15 14:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("missing_issues", "0010_watcheditem"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="watcheditem",
            unique_together={("user", "content_type", "object_id")},
        ),
    ]
