# Generated by Django 3.2.9 on 2022-01-23 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_issues', '0011_alter_watcheditem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ignoredissue',
            name='volume_comicvine_id',
            field=models.IntegerField(null=True),
        ),
    ]
