# Generated by Django 3.2.9 on 2025-01-27 18:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('missing_issues', '0016_apiqueue'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiqueue',
            name='added_in_queue',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
