# Generated by Django 3.2.9 on 2025-01-27 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('missing_issues', '0017_apiqueue_added_in_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiqueue',
            name='comicvine_id',
            field=models.IntegerField(),
        ),
    ]
