# Generated by Django 3.1.5 on 2021-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("objects", "0002_fk_m2m"),
    ]

    operations = [
        migrations.AddField(
            model_name="object",
            name="comicvine_last_match",
            field=models.DateTimeField(null=True),
        ),
    ]
