#!/bin/bash

#set -o errexit
#set -o pip0efail
#set -o nounset

python /app/manage.py clearqueue ${CLEAR_QUEUES}

celery -A config.celery_app worker -n ${WORKER_NAME:-celery}@%h -l INFO --autoscale=$AUTOSCALE -Q $QUEUES
