# Generated by Django 3.1.7 on 2021-03-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("locations", "0007_auto_20210315_1205"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="start_year",
            field=models.IntegerField(null=True),
        ),
    ]
