# Generated by Django 3.0.4 on 2020-03-25 16:14

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("concepts", "0002_fk_m2m"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concept",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, overwrite=True, populate_from=["name"]
            ),
        ),
    ]
