# Generated by Django 3.1.7 on 2021-03-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("concepts", "0006_concept_first_issue_comicvine_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="concept",
            name="comicvine_url",
            field=models.URLField(max_length=1000, null=True),
        ),
    ]
