#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset


python /app/manage.py migrate --noinput
python /app/manage.py clearqueue
python /app/manage.py collectstatic --noinput

echo ---${GUNICORN_CMD_ARGS}---

/usr/local/bin/gunicorn config.wsgi
