# Generated by Django 3.0.2 on 2020-03-24 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0002_fk_m2m"),
        ("locations", "0001_initial"),
        ("volumes", "0001_initial"),
        ("people", "0001_initial"),
        ("story_arcs", "0001_initial"),
        ("objects", "0001_initial"),
        ("teams", "0001_initial"),
        ("concepts", "0002_fk_m2m"),
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="characters",
            field=models.ManyToManyField(related_name="issues", to="characters.Character"),
        ),
        migrations.AddField(
            model_name="issue",
            name="characters_died",
            field=models.ManyToManyField(related_name="died_in_issues", to="characters.Character"),
        ),
        migrations.AddField(
            model_name="issue",
            name="concepts",
            field=models.ManyToManyField(related_name="issues", to="concepts.Concept"),
        ),
        migrations.AddField(
            model_name="issue",
            name="disbanded_teams",
            field=models.ManyToManyField(related_name="disbanded_in_issues", to="teams.Team"),
        ),
        migrations.AddField(
            model_name="issue",
            name="locations",
            field=models.ManyToManyField(related_name="issues", to="locations.Location"),
        ),
        migrations.AddField(
            model_name="issue",
            name="objects",
            field=models.ManyToManyField(related_name="issues", to="objects.Object"),
        ),
        migrations.AddField(
            model_name="issue",
            name="story_arcs",
            field=models.ManyToManyField(related_name="issues", to="story_arcs.StoryArc"),
        ),
        migrations.AddField(
            model_name="issue",
            name="teams",
            field=models.ManyToManyField(related_name="issues", to="teams.Team"),
        ),
        migrations.AddField(
            model_name="issue",
            name="volume",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="issues",
                to="volumes.Volume",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="IssuePerson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=100, null=True)),
                (
                    "issue",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="issues.Issue"),
                ),
                (
                    "person",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="people.Person"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="issue",
            name="authors",
            field=models.ManyToManyField(through="issues.IssuePerson", to="people.Person"),
        ),
    ]
