# Generated by Django 3.0.4 on 2020-03-24 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_fk_m2m"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="objects",
            new_name="objects_in",
        ),
    ]
