# Generated by Django 3.1.5 on 2021-03-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0005_volume_nullable"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="issue",
            options={"ordering": ("volume__name", "volume__start_year", "number")},
        ),
        migrations.AddField(
            model_name="issue",
            name="comicvine_last_match",
            field=models.DateTimeField(null=True),
        ),
    ]
