# Generated by Django 3.1.7 on 2021-03-11 11:30

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0006_auto_20210310_1910"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                overwrite=True,
                populate_from=[
                    "volume__publisher__name",
                    "volume__name",
                    "volume__start_year",
                    "number",
                    "name",
                ],
            ),
        ),
    ]
