# Generated by Django 3.1.7 on 2021-03-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0007_auto_20210311_1130"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="size",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="issue",
            name="space_key",
            field=models.CharField(default="", max_length=1000),
            preserve_default=False,
        ),
    ]
