# Generated by Django 3.1.7 on 2021-03-15 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0010_auto_20210315_1029"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="name",
            field=models.TextField(null=True),
        ),
    ]
