# Generated by Django 3.1.7 on 2021-03-29 23:19

from django.db import migrations, models
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0006_auto_20210329_2319"),
        ("issues", "0012_auto_20210315_1205"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="authors",
            field=models.ManyToManyField(related_name="issues", through="issues.IssuePerson", to="people.Person"),
        ),
        migrations.AlterField(
            model_name="issue",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=1000,
                overwrite=True,
                populate_from=[
                    "get_publisher_name",
                    "get_volume_name",
                    "get_volume_start_year",
                    "number",
                    "name",
                ],
            ),
        ),
    ]
