# Generated by Django 3.1.7 on 2021-04-03 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0013_auto_20210329_2319"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinishedIssue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("finish_date", models.DateField(auto_now=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="issues.issue"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("user", "issue")},
            },
        ),
        migrations.AddField(
            model_name="issue",
            name="finished_users",
            field=models.ManyToManyField(
                related_name="finished_issues",
                through="issues.FinishedIssue",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
