# Generated by Django 3.1.7 on 2021-04-05 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("people", "0006_auto_20210329_2319"),
        ("issues", "0014_auto_20210403_0120"),
    ]

    operations = [
        migrations.RenameField(
            model_name="issue",
            old_name="authors",
            new_name="people",
        ),
        migrations.AlterField(
            model_name="issueperson",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authors",
                to="issues.issue",
            ),
        ),
        migrations.AlterField(
            model_name="issueperson",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authored_issues",
                to="people.person",
            ),
        ),
    ]
