# Generated by Django 3.1.7 on 2021-04-05 11:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("issues", "0015_auto_20210405_0136"),
    ]

    operations = [
        migrations.AddField(
            model_name="issue",
            name="numerical_number",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="finishedissue",
            name="issue",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finished",
                to="issues.issue",
            ),
        ),
        migrations.AlterField(
            model_name="finishedissue",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finished",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
