# Generated by Django 3.2.9 on 2023-06-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0019_alter_finishedissue_finish_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issueperson',
            name='role',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
