import type { ThemeDefinition } from "vuetify"

export const staticPrimaryColor = "#7367F0"

export const themes: Record<string, ThemeDefinition> = {
  dark: {
    colors: {
      "background":               "#25293C",
      "error":                    "#EA5455",
      "grey-100":                 "#2F3349",
      "grey-200":                 "#26293A",
      "grey-300":                 "#4A5072",
      "grey-400":                 "#5E6692",
      "grey-50":                  "#26293A",
      "grey-500":                 "#7983BB",
      "grey-600":                 "#AAB3DE",
      "grey-700":                 "#B6BEE3",
      "grey-800":                 "#CFD3EC",
      "grey-900":                 "#E7E9F6",
      "info":                     "#00CFE8",
      "on-background":            "#D0D4F1",
      "on-info":                  "#fff",
      "on-primary":               "#fff",
      "on-secondary":             "#fff",
      "on-success":               "#fff",
      "on-surface":               "#D0D4F1",
      "on-warning":               "#fff",
      "perfect-scrollbar-thumb":  "#4A5072",
      "primary":                  staticPrimaryColor,
      "secondary":                "#A8AAAE",
      "skin-bordered-background": "#2f3349",
      "skin-bordered-surface":    "#2f3349",
      "success":                  "#28C76F",
      "surface":                  "#2F3349",
      "warning":                  "#FF9F43",
    },
    dark:      true,
    variables: {
      "activated-opacity":               0.16,
      "border-color":                    "#D0D4F1",
      "border-opacity":                  0.16,
      "code-color":                      "#d400ff",
      "disabled-opacity":                0.42,
      "dragged-opacity":                 0.1,
      "focus-opacity":                   0.12,
      "high-emphasis-opacity":           0.78,
      "hover-opacity":                   0.04,
      "medium-emphasis-opacity":         0.68,
      "overlay-scrim-background":        "#101121",
      "overlay-scrim-opacity":           0.6,
      "pressed-opacity":                 0.14,
      "selected-opacity":                0.06,
      // Shadows
      "shadow-key-umbra-color":          "#0F1422",
      "switch-checked-disabled-opacity": 0.3,
      "switch-disabled-thumb-opacity":   0.8,
      "switch-disabled-track-opacity":   0.4,
      "switch-opacity":                  0.4,

      "tooltip-background": "#5E6692",
    },
  },
  light: {
    colors: {
      "background":               "#F8F7FA",
      "error":                    "#EA5455",
      "grey-100":                 "#F5F5F5",
      "grey-200":                 "#EEEEEE",
      "grey-300":                 "#E0E0E0",
      "grey-400":                 "#BDBDBD",
      "grey-50":                  "#FAFAFA",
      "grey-500":                 "#9E9E9E",
      "grey-600":                 "#757575",
      "grey-700":                 "#616161",
      "grey-800":                 "#424242",
      "grey-900":                 "#212121",
      "info":                     "#00CFE8",
      "on-background":            "#2F2B3D",
      "on-info":                  "#fff",
      "on-primary":               "#fff",
      "on-secondary":             "#fff",
      "on-success":               "#fff",
      "on-surface":               "#2F2B3D",
      "on-warning":               "#fff",
      "perfect-scrollbar-thumb":  "#DBDADE",
      "primary":                  staticPrimaryColor,
      "secondary":                "#A8AAAE",
      "skin-bordered-background": "#fff",
      "skin-bordered-surface":    "#fff",
      "success":                  "#28C76F",
      "warning":                  "#FF9F43",
    },
    dark: false,

    variables: {
      "activated-opacity":               0.16,
      "border-color":                    "#2F2B3D",
      "border-opacity":                  0.16,
      "code-color":                      "#d400ff",
      "disabled-opacity":                0.42,
      "dragged-opacity":                 0.1,
      "focus-opacity":                   0.12,
      "high-emphasis-opacity":           0.78,
      "hover-opacity":                   0.04,
      "medium-emphasis-opacity":         0.68,
      "overlay-scrim-background":        "#4C4E64",
      "overlay-scrim-opacity":           0.5,
      "pressed-opacity":                 0.14,
      "selected-opacity":                0.06,
      // Shadows
      "shadow-key-umbra-color":          "#2F2B3D",
      "switch-checked-disabled-opacity": 0.3,
      "switch-disabled-thumb-opacity":   0.4,
      "switch-disabled-track-opacity":   0.3,
      "switch-opacity":                  0.2,

      "tooltip-background": "#4A5072",
    },
  },
}

export default themes
