name: Deploy to YC

on:
  workflow_call:
    inputs:
      env_name:
        type: string
        required: true
      working_dir:
        description: working directory with docker compose file
        default: "~/read_comics"
        type: string
        required: false
      yc_path:
        default: "/home/docker/yandex-cloud/bin"
        type: string
        required: false
      script:
        default: "./pull_and_restart.sh"
        type: string
        required: false

jobs:
  start_vm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Script permissions
        run: chmod +x ./.github/workflows/scripts/start_yc_vm.sh

      - name: IAM Token
        id: get_token
        uses: yc-actions/yc-iam-token@v1
        with:
          yc-sa-json-credentials: ${{ secrets.YC_SECRET }}

      - name: Start VM
        run: ./.github/workflows/scripts/start_yc_vm.sh "${{ steps.get_token.outputs.token }}" "${{ secrets.YC_INSTANCE_ID }}"

  deploy:
    runs-on: ubuntu-latest
    needs: start_vm
    environment: ${{ inputs.env_name }}
    steps:
      - name: Deploy to Yandex Cloud VM via SSH action
        uses: appleboy/ssh-action@v0.1.3
        with:
          HOST: ${{ secrets.YC_HOST }}
          USERNAME: ${{ secrets.YC_USER }}
          KEY: ${{ secrets.YC_SSH_KEY }}
          script: |
            cd ${{ inputs.working_dir }}
            export PATH="$PATH:${{ inputs.yc_path }}"
            ${{ inputs.script }}
