name: Current version

permissions:
  checks: none
  pull-requests: none

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: "main"
    paths-ignore: [ "docs/**" ]
    tags-ignore: [ "v*" ]

jobs:
  qa:
    uses: ./.github/workflows/qa.yml
  publish_reports:
    uses: ./.github/workflows/publish_reports.yml
    if: success() || failure()
    needs: qa
    with:
      publish_test_report: false
    secrets: inherit
