name: Next version

permissions:
  checks: none
  pull-requests: none

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: "develop"

jobs:
  qa:
    uses: ./.github/workflows/qa.yml
    with:
      silent_linters: true
    secrets: inherit
    permissions:
      checks: none
      pull-requests: none
  publish_reports:
    uses: ./.github/workflows/publish_reports.yml
    if: ${{ success() || failure() }}
    needs: qa
    with:
      publish_test_report: false
      sonar_scan_name: SonarCloud - Develop
    secrets: inherit
    permissions:
      checks: none
  publish:
    uses: ./.github/workflows/publish.yml
    secrets: inherit
    permissions:
      checks: none
      pull-requests: none
  deploy:
    uses: ./.github/workflows/deploy_yc.yml
    needs: publish
    with:
      env_name: "next"
    secrets: inherit
    permissions:
      checks: none
      pull-requests: none
