name: Pull request

permissions:
  checks: write
  pull-requests: write

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  pull_request:
    branches:
      - main

jobs:
  qa:
    uses: ./.github/workflows/qa.yml
    permissions:
      checks: write
      pull-requests: write
    with:
      silent_linters: true
  publish_reports:
    uses: ./.github/workflows/publish_reports.yml
    if: success() || failure()
    needs: qa
    secrets: inherit
    permissions:
      checks: write
      pull-requests: write
