name: Release

permissions:
  checks: write

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  push:
    branches: "main"
    paths-ignore: [ "docs/**" ]

jobs:
  publish_backend:
    uses: ./.github/workflows/publish_image.yml
    with:
      image_name: "backend"
    secrets: inherit
  deploy:
    uses: ./.github/workflows/deploy_yc.yml
    needs: publish_backend
    with:
      env_name: "next"
    secrets: inherit
