name: Release

permissions:
  checks: write

# Enable Buildkit and let compose use it to speed up image building
env:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

on:
  release:
    types: [published]

jobs:
  publish:
    uses: ./.github/workflows/publish_image.yml
    with:
      tag_latest: true
      release: ${{ github.ref_name }}
    secrets: inherit
  deploy:
    uses: ./.github/workflows/deploy_yc.yml
    needs: publish
    with:
      env_name: "production"
    secrets: inherit
