name: Unit tests

on:
  workflow_call:

jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v3

      - name: Generate .django_unsafe
        run: |
          touch .envs/.local/.django_unsafe
          echo "DO_SPACE_DATA_KEY=test" >> .envs/.local/.django_unsafe
          echo "DO_SPACE_DATA_SECRET=test" >> .envs/.local/.django_unsafe
          echo "COMICVINE_API_KEY=test" >>  .envs/.local/.django_unsafe

      - name: Build the Stack
        run: docker-compose -f local.yml build

      - name: Run Django Tests
        run: docker-compose -f local.yml run --rm django pytest --cov read_comics --cov-report xml:coverage.xml --cov-report term --cov-config=setup.cfg --junitxml=test_report.xml || true

      - name: Save Coverage report artifact
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: coverage_report
          path: coverage.xml

      - name: Save test report artifact
        if: success() || failure()
        uses: actions/upload-artifact@v3
        with:
          name: test_report
          path: test_report.xml

      - name: Tear down the Stack
        if: success() || failure()
        run: docker-compose -f local.yml down
